// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFGITbkDdyVIoiq3qhUKIs6a14M0Qw7k0',
    appId: '1:718105384999:web:a993476a385f682626d602',
    messagingSenderId: '718105384999',
    projectId: 'fir-task-96a07',
    authDomain: 'fir-task-96a07.firebaseapp.com',
    storageBucket: 'fir-task-96a07.appspot.com',
    measurementId: 'G-KBQ9HWZ9PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBriSb-eixMvUZ5vQNdqQqs94I0gYY-21A',
    appId: '1:718105384999:android:5c1d36f96495667d26d602',
    messagingSenderId: '718105384999',
    projectId: 'fir-task-96a07',
    storageBucket: 'fir-task-96a07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbiCIoTswPeNU772MPxOvFlsJAUMxoWfc',
    appId: '1:718105384999:ios:8cd140b33970d06826d602',
    messagingSenderId: '718105384999',
    projectId: 'fir-task-96a07',
    storageBucket: 'fir-task-96a07.appspot.com',
    iosClientId: '718105384999-pvfbpdrcfdqe018bql5ru453k0dedvbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.plateMentor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbiCIoTswPeNU772MPxOvFlsJAUMxoWfc',
    appId: '1:718105384999:ios:49d8c2a85349302426d602',
    messagingSenderId: '718105384999',
    projectId: 'fir-task-96a07',
    storageBucket: 'fir-task-96a07.appspot.com',
    iosClientId: '718105384999-b25u2pde7rvaqik2fkaoqfqm55ismftc.apps.googleusercontent.com',
    iosBundleId: 'com.example.plateMentor.RunnerTests',
  );
}
